```{r echo=FALSE}
###############################################
##                                           ##
## (c) Andrej Blejec (andrej.blejec@nib.si)  ##
##                                           ##
###############################################
```
```{r echo=FALSE,results='hide'}
options(width=70)
```

## Network for `r thisTreat`.

```{r }
filter <- pdata$Treatment %in% thisTreat
XX1 <- lapply(CCDATA, function(x) if(is.null(dim(x))) x[filter] else 
x[filter,])
table(XX1$status)
```

```{r }
res1 <- block.splsda(X = XX1[-1]
    , Y = as.factor(XX1[[1]])
    , ncomp = ncomp
    , keepX = list.keepX
    , design = design
    )

```

```{r results='asis'}
cutoff <- 0.0
x <- res1
layout.fun <- NULL
label <-thisTreat
out23b <- ""
  out23b <- paste( out23b, knit_child("035b-multipartite-network.Rmd", 
  quiet=TRUE))
RETURN <- nw  # complete network
cat(out23b)
```

Save network layout for further plots, used by layout function `my.layout`.
```{r }
ly <- nw$layout
```

```{r results='asis'}
cutoff <- 0.7
x <- res1
layout.fun <- my.layout
label <- thisTreat
out23b <- ""
  out23b <- paste( out23b, knit_child("035b-multipartite-network.Rmd", 
  quiet=TRUE))
cat(out23b)
```

