---
title: "Untitled"
author: "A. Blejec"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
moti <- c("CLCdnDe10_24187",	"VdnPW4_15664")

```

```{r}
remove_NA_pairs <- function(x, verbose=TRUE){
      X <- x
      print(ncol(X))
      a <- expand.grid(1:ncol(X),1:ncol(X))
    nas <- apply(a,1,function(x) X[,x[1]]+X[,x[2]])
    nas <- apply(nas,2,function(x) all(is.na(x)))
    gnile <- unlist(a[nas,][1,])
    print(dimnames(X)[[2]][gnile])
    X <- X[,-gnile]
    return(X)
}
bla <- remove_NA_pairs(XDat)
dim(bla)
```

### Remove columns with NAs in pairs

```{r}
for( in in 2:length(X) ) {  
  cat(names(X)[i],"\n\n")
  yyy <- X[[i]]
  xxx <- remove_NA_pairs(yyy, verbose=TRUE)
  dim(xxx)
  dim(yyy)
}

```






## R Markdown
```{r}
comp <- 1:5
object <- final.diablo.model
 X = object$X
 X[[1]][1:10,1:10]
    Y = object$Y
    indY = object$indY
    object$variates = c(object$variates[-indY], object$variates[indY])
    object$loadings = c(object$loadings[-indY], object$loadings[indY])
    object$loadings = lapply(object$loadings, function(x) {
        x[, comp, drop = FALSE]
    })
    keepA = lapply(object$loadings, function(i) apply(abs(i), 
        1, sum) > 0)
    keeps <- lapply(object$loadings, function(i) apply(abs(i), 
        1, sum))
    XDatList = mapply(function(x, y) {
      print
        x[, y]
    }, x = X, y = keepA[-length(keepA)], SIMPLIFY = FALSE)
    XDatList[[1]][1:10,1:10]
    XDat = do.call(cbind, XDatList)
    XDat[which(XDat > 2)] = 2
    XDat[which(XDat < -2)] = -2
    VarLabels = factor(rep(names(X), lapply(keepA[-length(keepA)], 
        sum)), levels = names(X))
    opar = par()[!names(par()) %in% c("cin", "cra", 
        "csi", "cxy", "din", "page")]
    par(mfrow = c(1, 1))
    margins = c(2, 15)
    print(XDat[,moti])
    slab <- match(moti,dimnames(XDat)[[2]])

```


```{r}
XDat <- remove_NA_pairs(XDat)
    cimres <- cim(XDat,cluster="both")
    M <- cimres$mat
    print(cimres$mat[1:10,1:10])
    comp
    which(is.na(cimres$mat), arr.ind=TRUE)

```

```{r}
my.cimDiablo <- 
function (object, color = NULL, color.Y, color.blocks, comp = NULL, 
    margins = c(2, 15), legend.position = "topright", transpose = FALSE, 
    row.names = TRUE, col.names = TRUE, size.legend = 1.5, ...) 
{
    if (!is(object, "block.splsda")) 
        stop("cimDiablo is only available for 'block.splsda' objects")
    if (length(object$X) <= 1) 
        stop("This function is only available when there are more than 3 blocks")
    ncomp = min(object$ncomp)
    if (is.null(comp)) {
        comp = 1:ncomp
    }
    if (length(comp) > 1) {
        comp = unique(comp)
        if (!is.numeric(comp) || any(comp < 1)) 
            stop("invalid vector for 'comp'.", call. = FALSE)
        if (any(comp > ncomp)) 
            stop("the elements of 'comp' must be smaller or equal than ", 
                ncomp, ".", call. = FALSE)
    }
    if (length(comp) == 1) {
        if (is.null(comp) || !is.numeric(comp) || comp <= 0 || 
            comp > ncomp) 
            stop("invalid value for 'comp'.", call. = FALSE)
        comp = c(comp, comp)
    }
    comp = round(comp)
    if (missing(color.Y)) {
        color.Y = color.mixo(1:nlevels(object$Y))
    }
    else {
        if (length(color.Y) != nlevels(object$Y)) 
            stop("'color.Y' needs to be of length ", nlevels(object$Y))
    }
    if (missing(color.blocks)) {
        color.blocks = brewer.pal(n = 12, name = "Paired")[seq(2, 
            12, by = 2)]
    }
    else {
        if (length(color.blocks) != length(object$X)) 
            stop("'color.blocks' needs to be of length ", 
                length(object$X))
    }
    X = object$X
    Y = object$Y
    indY = object$indY
    object$variates = c(object$variates[-indY], object$variates[indY])
    object$loadings = c(object$loadings[-indY], object$loadings[indY])
    object$loadings = lapply(object$loadings, function(x) {
        x[, comp, drop = FALSE]
    })
    keepA = lapply(object$loadings, function(i) apply(abs(i), 
        1, sum) > 0)
    XDatList = mapply(function(x, y) {
        x[, y]
    }, x = X, y = keepA[-length(keepA)], SIMPLIFY = FALSE)
    XDat = do.call(cbind, XDatList)
    XDat[which(XDat > 2)] = 2
    XDat[which(XDat < -2)] = -2
    VarLabels = factor(rep(names(X), lapply(keepA[-length(keepA)], 
        sum)), levels = names(X))
    opar = par()[!names(par()) %in% c("cin", "cra", 
        "csi", "cxy", "din", "page")]
    par(mfrow = c(1, 1))
    #XDat[is.na(XDat)] <- 0
    print(XDat[,1:8])
    res <- cim(XDat, transpose = transpose, color = color, row.names = row.names, 
        col.names = col.names, col.sideColors = color.blocks[as.numeric(VarLabels)], 
        row.sideColors = color.Y[as.numeric(Y)], margins = margins, 
        ...)
    print(res$mat[1:10,1:10])
    print(which(is.na(cimres$mat), arr.ind=TRUE))
    if (!transpose) {
        legend(legend.position, c("Rows", c(levels(Y)[order(levels(Y))], 
            "", "Columns", names(X))), col = c(1, 
            color.Y, 1, 1, color.blocks[1:nlevels(VarLabels)][match(levels(VarLabels), 
                names(X))]), pch = c(NA, rep(19, nlevels(Y)), 
            NA, NA, rep(19, nlevels(VarLabels))), bty = "n", 
            cex = size.legend, text.font = c(2, rep(1, nlevels(Y)), 
                NA, 2, rep(1, nlevels(VarLabels))))
    }
    else {
        legend(legend.position, c("Rows", names(X), "", 
            "Columns", c(levels(Y)[order(levels(Y))])), 
            col = c(1, color.blocks[1:nlevels(VarLabels)][match(levels(VarLabels), 
                names(X))], 1, 1, color.Y), pch = c(NA, rep(19, 
                nlevels(VarLabels)), NA, NA, rep(19, nlevels(Y))), 
            bty = "n", cex = size.legend, text.font = c(2, 
                rep(1, nlevels(VarLabels)), NA, 2, rep(1, nlevels(Y))))
    }
    par(opar)
    return(invisible(res))
}

```

```{r}
#dump("cim","cim.R")
```

