---
title: "04_LOOgraphs"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: yes
    toc_depth: 2
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

load('01.RData')

omics = merge(qPCR, met, 
              by = c("Treatment", "SamplingDay", "PlantNo"), 
              all.x = FALSE, all.y = FALSE)
omics = merge(omics, horm, 
              by = c("Treatment", "SamplingDay", "PlantNo"), 
              all.x = FALSE, all.y = FALSE)

omics$SamplingDay = as.numeric(omics$SamplingDay)

omics = omics[order(omics$Treatment, omics$SamplingDay, omics$PlantNo), ]

keep = grep('Treatment|SamplingDay|PlantNo', colnames(omics), invert = TRUE)

v = colnames(omics[, keep])

```


```{r}

library(igraph)

# https://stackoverflow.com/questions/15933958/collapse-concatenate-aggregate-a-column-to-a-single-comma-separated-string-w

toString.X <- function (x, width = NULL) {
  y = sort(unique(x))
    string <- paste(y, collapse = ", ")
    if (missing(width) || is.null(width) || width == 0) 
        return(string)
    if (width < 0) 
        stop("'width' must be positive")
    if (nchar(string, type = "w") > width) {
        width <- max(6, width)
        string <- paste0(strtrim(string, width - 4), "....")
    }
    string
}

autocurve.edges <- function(graph, start=0.5) {
      el <- apply(get.edgelist(graph, names = FALSE), 1, paste, collapse = ":")
      ave(rep(NA, length(el)), el, FUN = function(x) {
        if (length(x) == 1) {
          return(0)
        } else {
          return(seq(-start, start, length = length(x)))
        }
      })
}



```



# |0.95| within Treatment/SamplingDay

```{r}


mycut = 0.95


cormat0 = cor(as.matrix(omics[, keep]), use = 'na.or.complete')
m0 = as.data.frame(which(abs(cormat0) >= mycut, arr.ind=TRUE))
m0 = m0[m0[, 1] != m0[, 2], ]
colnames(m0) = c('from', 'to')
m0 = data.table::data.table(m0)
data.table::setkey(m0, 'from', 'to')
m0[,"index0" := .I]


n = expand.grid(unique(omics$Treatment), unique(omics$SamplingDay))

n$Var2 = as.numeric(n$Var2)
n = n[order(n$Var1, n$Var2), ]

n = n[n$Var2 %in% c(1, 8), ]

loo = vector("list", nrow(n))
names(loo) = paste(n[, 1], n[, 2], sep = '_')

for (k in 1:nrow(n)){
  
  print(k)
  
  i = n[k, 2]
  j = as.character(n[k, 1])
  

  
  m1 = NULL
  m2 = NULL

  cormat1 = cor(as.matrix(omics[omics$SamplingDay == i, keep]), use = 'na.or.complete')
  m1 = as.data.frame(which(abs(cormat1) >= mycut, arr.ind=TRUE))
  m1 = m1[m1[, 1] != m1[, 2], ]
  colnames(m1) = c('from', 'to')
  m1 = data.table::data.table(m1)
  data.table::setkey(m1, 'from', 'to')
  m1[,"index1" := .I]
  

    cat(j, i, '\n')
    
    par(mfrow = c(2,3))
    
      qgraph::qgraph(cormat0, 
                   shape='circle', 
                   posCol='darkred', 
                   negCol='darkblue',
                   layout='spring', 
                   vsize=5, 
                   cut = mycut,
                   details = TRUE, 
                   curveAll = TRUE,
                   title = 'All',
                   minimum = mycut,
                   labels = colnames(cormat0))
          qgraph::qgraph(cormat1, 
                   shape='circle', 
                   posCol='darkred', 
                   negCol='darkblue',
                   layout='spring', 
                   vsize=5, 
                   cut = mycut, 
                   details = TRUE, 
                   curveAll = TRUE,
                   title = paste('Tp:', i),
                   minimum = mycut,
                   labels = colnames(cormat1))
    
    cormat2 = cor(as.matrix(omics[(omics$SamplingDay == i) & (omics$Treatment != j) , keep]), use = 'na.or.complete')
    m2 = as.data.frame(which(abs(cormat2) >= mycut, arr.ind=TRUE))
    m2 = m2[m2[, 1] != m2[, 2], ]
    colnames(m2) = c('from', 'to')
    m2 = data.table::data.table(m2)
    data.table::setkey(m2, 'from', 'to')
    m2[,"index2" := .I]


    qgraph::qgraph(cormat2, 
                   shape='circle', 
                   posCol='darkred', 
                   negCol='darkblue',
                   layout='spring', 
                   vsize=5, 
                   cut = mycut,
                   details = TRUE, 
                   curveAll = TRUE,
                   title = paste('LOO:', j, i),
                   minimum = mycut,
                   labels = colnames(cormat2)
                   )
    
      m5 = m0[m1]
      unique2 = m5[is.na(index0)==TRUE & is.na(index1)==FALSE,]
      
      tmp = as.data.frame(cbind(1:length(v), v))
      colnames(tmp) = c('from', 'name1')
      tmp$from = as.numeric(tmp$from)
      unique2 = merge(unique2, tmp, by = 'from', all.x = TRUE, all.y = FALSE)
      colnames(tmp) = c('to', 'name2')
      tmp$to = as.numeric(tmp$to)
      unique2 = merge(unique2, tmp, by = 'to', all.x = TRUE, all.y = FALSE)
      g1v = as.data.frame(rbind(cbind(unique2$from, unique2$name1),
                                cbind(unique2$to, unique2$name2)))
      g1v = g1v[!duplicated(g1v), ]
      colnames(g1v) = c('id', 'name')
      g1v$id = as.numeric(g1v$id)
      unique2 = unique2[, c(2,1,5,6,3,4)]
      
      
      if(nrow(unique2) > 0){
          g1 = igraph::graph_from_edgelist(as.matrix(unique2[, 1:2]), 
                                           directed = TRUE)
          gg1 = igraph::subgraph(g1, vids = g1v$id)
          plot(gg1, #layout=igraph::layout_with_fr, 
               layout= igraph::layout_with_kk,
               vertex.size = 4,
               vertex.label.dist=0.5, 
               vertex.color="red", 
               edge.arrow.size=0.05,
               vertex.label = g1v$name,
               vertex.label.cex = 1,
               main = paste('All - Tp', i),
               edge.curved = autocurve.edges(gg1)) 
          
      } else {
        plot(1, type = "n",
             yaxt='n', xaxt='n', ann=FALSE, bty='n',
             xlab = "", ylab = "")
      par(mfrow = c(1,1))
      }
      


      m5 = m0[m2]
      unique2 = m5[is.na(index0)==TRUE & is.na(index2)==FALSE,]
      
      tmp = as.data.frame(cbind(1:length(v), v))
      colnames(tmp) = c('from', 'name1')
      tmp$from = as.numeric(tmp$from)
      unique2 = merge(unique2, tmp, by = 'from', all.x = TRUE, all.y = FALSE)
      colnames(tmp) = c('to', 'name2')
      tmp$to = as.numeric(tmp$to)
      unique2 = merge(unique2, tmp, by = 'to', all.x = TRUE, all.y = FALSE)
      g1v = as.data.frame(rbind(cbind(unique2$from, unique2$name1),
                                cbind(unique2$to, unique2$name2)))
      g1v = g1v[!duplicated(g1v), ]
      colnames(g1v) = c('id', 'name')
      g1v$id = as.numeric(g1v$id)
      unique2 = unique2[, c(2,1,5,6,3,4)]
      
      
      if(nrow(unique2) > 0){
          g1 = igraph::graph_from_edgelist(as.matrix(unique2[, 1:2]), 
                                           directed = TRUE)
          gg1 = igraph::subgraph(g1, vids = g1v$id)
          plot(gg1, #layout=igraph::layout_with_fr, 
               layout= igraph::layout_with_kk,
               vertex.size = 4,
               vertex.label.dist=0.5, 
               vertex.color="red", 
               edge.arrow.size=0.05,
               vertex.label = g1v$name,
               vertex.label.cex = 1,
               main = paste('All -', j, i),
               edge.curved = autocurve.edges(gg1)) 
          
      } else {
        plot(1, type = "n",
             yaxt='n', xaxt='n', ann=FALSE, bty='n',
             xlab = "", ylab = "")
      par(mfrow = c(1,1))
      }
      
      m5 = m1[m2]
      overlap = m5[is.na(index1)==FALSE & is.na(index2)==FALSE,]
      unique2 = m5[is.na(index1)==TRUE & is.na(index2)==FALSE,]
      
      # all(v == row.names(cormat2))
      # all(v == colnames(cormat2))
      tmp = as.data.frame(cbind(1:length(v), v))
      colnames(tmp) = c('from', 'name1')
      tmp$from = as.numeric(tmp$from)
      unique2 = merge(unique2, tmp, by = 'from', all.x = TRUE, all.y = FALSE)
      colnames(tmp) = c('to', 'name2')
      tmp$to = as.numeric(tmp$to)
      unique2 = merge(unique2, tmp, by = 'to', all.x = TRUE, all.y = FALSE)
      g1v = as.data.frame(rbind(cbind(unique2$from, unique2$name1),
                                cbind(unique2$to, unique2$name2)))
      g1v = g1v[!duplicated(g1v), ]
      colnames(g1v) = c('id', 'name')
      g1v$id = as.numeric(g1v$id)
      unique2 = unique2[, c(2,1,5,6,3,4)]
      
      
      if(nrow(unique2) > 0){
          g1 = igraph::graph_from_edgelist(as.matrix(unique2[, 1:2]), 
                                           directed = TRUE)
          gg1 = igraph::subgraph(g1, vids = g1v$id)
          l1 = layout_on_grid(gg1, dim = 2)
          l2 = layout_with_kk(gg1, 
                              coords = l1, dim = 2,
                              maxiter = 999 * vcount(gg1),
                              epsilon = 0, kkconst = vcount(gg1),
                              #weights = rep(100, length.out),
                              minx = NULL, maxx = NULL,
                              miny = NULL, maxy = NULL,
                              minz = 0, maxz = 0)

          plot(gg1, #layout=igraph::layout_with_fr, 
               layout = l2,
               vertex.size = 4,
               vertex.label.dist=0.5, 
               vertex.color="red", 
               edge.arrow.size=0.05,
               vertex.label = g1v$name,
                vertex.label.cex = 1,
               main = paste('Tp', i, '- LOO', j, i),
               edge.curved = autocurve.edges(gg1)) 
          
          loo[[k]] = igraph::get.edgelist(g1) # keep oroginal order ID

      } else {
        plot(1, type = "n",
             yaxt='n', xaxt='n', ann=FALSE, bty='n',
             xlab = "", ylab = "")
      }

          plot(1, type = "n",
             yaxt='n', xaxt='n', ann=FALSE, bty='n',
             xlab = "", ylab = "")
      par(mfrow = c(1,1))
  
  par(mfrow = c(1,1))
  
  
  
}


par(mfrow = c(1,1))

# sanity check
# tmp = which(abs(cormat2) >= mycut, arr.ind=TRUE)
# tmp = tmp[tmp[, 1] != tmp[,2], ]
# tmp = tmp[order(tmp[,1], tmp[,2]), ]
# all(tmp == m2[, 1:2])


```


```{r}


sapply(loo, nrow)

df = NULL
for (i in 1:length(loo)){
  tmp = as.data.frame(loo[[i]])
  if (nrow(tmp) > 0){
    tmp$Treatment = gsub('_.*', '', names(loo)[i])
    tmp$SamplingDay = gsub('.*_', '', names(loo)[i])
    df = rbind(df, tmp)
  } else cat('No edges in: ', names(loo)[i], '\n')

}


df$SamplingDay = stringr::str_pad(as.numeric(df$SamplingDay), 2, pad = "0")
sort(unique(df$SamplingDay))
df = df[order(df$Treatment, df$SamplingDay), ]
df$TreatmentSamplingDay = paste0(df$Treatment, df$SamplingDay)


a = aggregate(TreatmentSamplingDay ~., df[, c(1:2, 5)], FUN=toString.X)
b = aggregate(Treatment ~., df[, c(1:2, 3)], toString.X)
d = aggregate(SamplingDay ~., df[, c(1:2, 4)], toString.X)
tmp = merge(a, b, by = c('V1', 'V2'), all.x = TRUE, all.y = TRUE)
tmp = merge(tmp, d, by = c('V1', 'V2'), all.x = TRUE, all.y = TRUE)
g = df
df = tmp


colnames(df)[1:2] = c('nodeID1', 'nodeID2')

vertices = cbind(1:length(v), v)

colnames(vertices) = c('nodeID2', 'nodeName2')
df = merge(df, vertices, by = 'nodeID2', all.x = TRUE, all.y = FALSE)

colnames(vertices) = c('nodeID1', 'nodeName1')
df = merge(df, vertices, by = 'nodeID1', all.x = TRUE, all.y = FALSE)

df$shortName1 = df$nodeName1
df$shortName2 = df$nodeName2
df = df[, c(1:2, 7:6, 8:9, 3:5)]

table(df$TreatmentSamplingDay)
table(df$Treatment)
table(df$SamplingDay)


```


```{r}

names = as.data.frame(rbind(cbind(df$nodeID1, df$nodeName1, df$shortName1),
                            cbind(df$nodeID2, df$nodeName2, df$shortName2)))
names = names[!duplicated(names), ]
names[, 1] = as.numeric(names[, 1])
names = names[order(names$V1), ]
colnames(names) = c('id', 'name', 'shortName')


g1 = igraph::graph_from_edgelist(as.matrix(df[, 1:2]),
                                 directed = TRUE)
V(g1)$name = v
plot(g1,
     layout = layout_with_fr(g1),
     vertex.label = V(g1)$name,
     vertex.label.cex = 0.5,
     # layout= igraph::layout_with_kk,
     vertex.size = 6,
     vertex.label.dist=0.5,
     vertex.color="yellow",
     edge.arrow.size=0.05)
gg1 = igraph::subgraph(g1, vids = names$id)
V(gg1)
ind = match(V(gg1)$name, names$name)
all(V(gg1)$name == names$name)
V(gg1)$shortName = names$shortName
plot(gg1,
     layout = layout_with_fr(gg1),
     vertex.label = V(gg1)$name,
     vertex.label.cex = 0.5,
     # layout= igraph::layout_with_kk,
     vertex.size = 6,
     vertex.label.dist=0.5,
     vertex.color="yellow",
     edge.arrow.size=0.05)
g1 = gg1

l1 = layout_on_grid(g1, dim = 2)
l2 = layout_with_kk(g1, coords = l1, dim = 2,
                            maxiter = 999 * vcount(g1),
                            epsilon = 0, kkconst = vcount(g1),
                            #weights = rep(100, length.out),
                            minx = NULL, maxx = NULL,
                            miny = NULL, maxy = NULL,
                            minz = 0, maxz = 0)
z = round(ecount(g1)/vcount(g1))
l2 = l2*2*z^z
V(g1)$x <- as.numeric(l2[,1])
V(g1)$y <- as.numeric(l2[,2])
mydeg = igraph::degree(g1, loops = FALSE, normalized = FALSE,  mode = "all")
V(g1)$degree <- mydeg
# g1
#
#
#
# V(g1)
#
#
# V(g1)$name
# V(g1)$shortName

plot(0, type = "n",
     axes = FALSE,
     xlim = extendrange(V(g1)$x),
     ylim = extendrange(V(g1)$y),
     xlab = '',
     ylab = '',
     main = paste('Treatments', mycut))

plot(g1,
     layout = cbind(V(g1)$x, V(g1)$y),
     edge.label = '',
     vertex.label = V(g1)$shortName,
     vertex.color = 'yellow',
     rescale = FALSE,
     add = TRUE,
     vertex.label.cex = 0.75,
     edge.arrow.size = 0.5,
     edge.arrow.width = 0.5,
     edge.lty = 'solid',
     edge.color = 'gray',
     edge.width = 0.25,
     edge.label.cex = 0.25,
     edge.curved = autocurve.edges(g1),
     main = paste('Treatments', mycut),
     vertex.size = 6)#V(g1)$degree)


# get.vertex.attribute(g1)
# get.edge.attribute(g1)


```


```{r}


e.l. = as.data.frame(get.edgelist(g1))
colnames(e.l.) = c('nodeName1', 'nodeName2')
e.l. = e.l.[order(e.l.$nodeName1, e.l.$nodeName2), ]
df$nodeID1 = as.numeric(df$nodeID1)
df$nodeID2 = as.numeric(df$nodeID2)
df = df[order(df$nodeName1, df$nodeName2), ]
all(e.l. == df[, 3:4])
df = df[order(df$nodeID1, df$nodeID2), ]

df$pair = NULL
for(i in 1:nrow(df)){
  df$pair[i] = paste(sort(c(as.numeric(df[i , 1]), as.numeric(df[i, 2]))), collapse =  '_')
}

df = df[!duplicated(df$pair), ]
df = df[, -ncol(df)]


fpo = file.path('..', 'output', 'cyto_LOO_input')
dir.create(fpo)
fn = paste0("loo_", mycut, "_net-all.xlsx")
xlsx::write.xlsx(df,
                 file = file.path(fpo,
                                  fn),
                 sheetName="loo_net",
                 row.names = FALSE)


omics.means = aggregate(.~Treatment*SamplingDay, omics[, -grep('PlantNo', colnames(omics))], mean)
omics.means$SamplingDay = stringr::str_pad(as.numeric(omics.means$SamplingDay), 2, pad = "0")
omics.means$TreatmentSamplingDay = paste0(omics.means$Treatment, omics.means$SamplingDay)
omics.means = omics.means[, -grep('^Treatment$|^SamplingDay$', colnames(omics.means))]
rownames(omics.means) = omics.means[, ncol(omics.means)]
omics.means = omics.means[, -ncol(omics.means)]
tmp = t(omics.means)
omics.means = cbind(rownames(tmp), tmp)
colnames(omics.means)[1] = 'name'

node.attr = do.call(cbind.data.frame, get.vertex.attribute(g1))

dim(omics.means)
omics.means = merge(node.attr, omics.means, by = 'name', all.x = TRUE, all.y = FALSE)
dim(omics.means)

# colnames(names) = c('id', 'name', 'shortName')

omics.means = merge(names[, -3], omics.means, by = 'name', all.x = TRUE, all.y = TRUE)
omics.means$id = as.numeric(omics.means$id)
omics.means = omics.means[order(omics.means$id), ]

all(omics.means$name == v[omics.means$id])

```



```{r}

g = g[, -grep('^Treatment$|^SamplingDay$', colnames(g))]
colnames(g)[1:2] = c('from', 'to')
colnames(names) = c('from', 'from_name', 'from_shortName')
g = merge(g, names, by = 'from', all.x = TRUE, all.y = TRUE)
colnames(names) = c('to', 'to_name', 'to_shortName')
g = merge(g, names, by = 'to', all.x = TRUE, all.y = TRUE)
g = g[, c(grep('from', colnames(g)),
          grep('to', colnames(g)),
          grep('TreatmentSamplingDay', colnames(g)))]
g = g[order(g$TreatmentSamplingDay), ]
st = sort(unique(g$TreatmentSamplingDay))

g$pair = NULL
for(i in 1:nrow(g)){
  g$pair[i] = paste(sort(c(as.numeric(g$from[i]), as.numeric(g$to[i]))), g$TreatmentSamplingDay[i], collapse =  '_')
}

g = g[!duplicated(g$pair), ]
g = g[, -ncol(g)]

ind = grep('degree', colnames(omics.means)) + 1
tmp = omics.means[ind:ncol(omics.means)]
tmp = apply(tmp, 2, as.numeric)
rownames(tmp) = omics.means$name

scaled = as.data.frame(t(apply(tmp, 1, scales::rescale)))
apply(scaled, 1, range)
colnames(scaled) = paste0(colnames(scaled), '_scaled')
colnames(scaled) = paste0(colnames(tmp), '_scaled-means')
scaled$name = rownames(tmp)
omics.means = merge(omics.means, scaled, by = 'name', all.x = TRUE, all.y = FALSE)

fn = paste0("loo_", mycut, "_net_nodes.xlsx")
xlsx::write.xlsx(omics.means,
                 file = file.path(fpo,
                                  fn),
                 sheetName="loo_net_nodes",
                 row.names = FALSE)

for (i in st){

  subg = g[g$TreatmentSamplingDay == i, ]
  fn = paste0("loo_", mycut, "_net_edges_", i, ".xlsx")
  xlsx::write.xlsx(subg,
                 file = file.path(fpo,
                                  fn),
                 sheetName="loo_net_edges",
                 row.names = FALSE)


}


```


Next step: Cytoscape

Find oout more at <https://manual.cytoscape.org/en/stable/>


```{r}

devtools::session_info()

```

