---
title: "03.4_Phenomics-hyperspectral "
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 6
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png'), 
                      fig.align = 'center', 
                      fig.height = 6, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )

```



```{r, rm, echo=TRUE, results='hide', warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))

gc()
gc()

set.seed(123456)

```


# libraries


```{r, echo=TRUE, results='hide', warning=FALSE, message=FALSE}

library(ggplot2)
# remotes::install_github("rpkgs/gg.layers")

```


```{r, echo=TRUE, results='hide', warning=FALSE, message=FALSE}

mypallette = c('#7F7F7F', '#FFC000', '#C00000', '#ED7D31', '#4472C4', '#70AD47')

jitter = position_jitter(width = 0.5, height = 0.0)
dodge = position_dodge(width=2.5)

```



```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}

# adapted from <https://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/>

## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE = function(data=NULL, measurevar, groupvars=NULL, na.rm=TRUE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 = function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac = ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    # datac = rename(datac, c("mean" = measurevar))

    datac$se = datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult = qt(conf.interval/2 + .5, datac$N-1)
    datac$ci = datac$se * ciMult
    
    datac$cv = datac$sd/datac$mean
    

    return(datac)
}





```

# data

```{r, echo=TRUE, results='hide', warning=FALSE, message=FALSE}

ncol = 3

omicsLevel = 'HyperSpectral'

string = ''




fp = file.path('..', 'input')

fn = 'data_targeted.xlsx'


pheno = openxlsx::read.xlsx(xlsxFile = file.path(fp, fn),
                            sheet = 'phenomics-noninvasive',
                            startRow = 2,
                            colNames = TRUE,
                            rowNames = FALSE,
                            detectDates = FALSE,
                            skipEmptyRows = TRUE,
                            skipEmptyCols = TRUE,
                            rows = NULL,
                            cols = NULL,
                            check.names = FALSE,
                            sep.names = ".",
                            namedRegion = NULL,
                            na.strings = "NA",
                            fillMergedCells = FALSE)

colnames(pheno)[1] = 'Time'
pheno = pheno[, c(grep('Time|Treatment', colnames(pheno)),
                  grep("^PRI$|^NDVI$|^SIPI$|^MCARI$|^OSAVI$|^WATER1", colnames(pheno)))]

pheno = pheno[pheno$Time %in% c(4, 11, 18), ]

pheno$Treatment = factor(pheno$Treatment, levels = c("Control", "Drought",
                                                     "Heat",
                                                     "Heat + Drought",
                                                     "Waterlogging",
                                                     "Heat + Drought + Waterlogging"))
pheno$Time = factor(pheno$Time, levels = c(4, 11, 18))

fill = as.data.frame(pheno$Treatment)
colnames(fill) = 'fill'

pheno = cbind(fill, pheno)
pheno$fill[pheno$Time == 18 & pheno$Treatment %in% c("Control", "Drought",
                                                     "Heat",
                                                     "Heat + Drought",
                                                     "Waterlogging")] = 'Control'
pheno$fill[pheno$Time == 4 & pheno$Treatment %in% c("Drought")] = 'Control'
pheno$fill[pheno$Time == 4 & pheno$Treatment %in% c("Heat + Drought")] = 'Heat'
pheno$fill[pheno$Time == 4 & pheno$Treatment %in% c("Heat + Drought + Waterlogging")] = 'Heat'
pheno$fill[pheno$Time == 11 & pheno$Treatment %in% c("Heat + Drought + Waterlogging")] = 'Heat + Drought'

pheno.l = tidyr::gather(pheno, variable, measurement, colnames(pheno)[4]:colnames(pheno)[ncol(pheno)], factor_key=FALSE)

pheno.l.SE = summarySE(data = pheno.l, 
                      measurevar="measurement", 
                      groupvars=c("Treatment", "Time", "variable"), 
                      na.rm = TRUE)
  
  

```


# plot

```{r, echo=TRUE, warning=FALSE, message=FALSE}
  

p = ggplot(data = pheno.l,
                 aes(x = Time, y = measurement, colour = Treatment, fill = fill)) +
    gg.layers::geom_boxplot2(width = 0.8, width.errorbar = 0.1) +
          ggtitle(paste0(omicsLevel))  +

    theme_classic() +
      theme(legend.position = "right",
            legend.title = element_text(color = "black",
                                        size = 10,
                                        face = 2),
            legend.background = element_rect(fill = "grey90", # Background
                                           colour = 1)) +
      scale_colour_manual(name = "Treatment",
                          values = mypallette) +
          scale_fill_manual(name = "Treatment",
                          values = mypallette) +
     facet_wrap( ~ variable, ncol = ncol, drop = FALSE, scales="free_y") +
   theme(legend.key=element_blank(), legend.background=element_blank())
    


print(p)



```


# sessionInfo

```{r, echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()

```


