```{r echo=FALSE}
###############################################
##                                           ##
## (c) Andrej Blejec (andrej.blejec@nib.si)  ##
##                                           ##
###############################################
```
```{r echo=FALSE,results='hide'}
options(width=70)
```
Child: 035-Network.rnw
### Cutoff =`r cutoff, \Sexpr{paste(names(res$X)[pair])` }
```{r fig.cap=label}
datasets <- names(res$X)[pair]
set.seed(1234)
N <- network(res, cutoff=cutoff, blocks=pair, shape.node=c("rectangle","rectangle"))
label <- paste(paste(.treat, collapse=", "),"|",paste(datasets, collapse=", "),"; cutoff =",cutoff)
title(label,adj=1,outer=TRUE,line=-1)
```



```{r echo=FALSE}
my.color.GreenRed <- function (n, alpha = 1)
{
    if (length(n) > 1 || !is.finite(n))
        stop("'n' must be an integer positive value.",
            call. = FALSE)
    if (n < 1)
        stop("'n' must be an integer positive value.",
            call. = FALSE)
    if (length(alpha) > 1 || !is.finite(alpha))
        stop("'alpha' must be an numeric value in the range [0, 1].",
            call. = FALSE)
    if (alpha < 0 || alpha > 1)
        stop("'alpha' must be an numeric value in the range [0, 1].",
            call. = FALSE)
    alpha = round(255 * alpha)
    ramp = colorRampPalette(c("darkgreen", "green",
        "gray95", "red", "darkred"))
    ramp = ramp(101)
    green = ramp[1:43]
    red = ramp[59:101]
    ramp = colorRamp(c(green, "gray95", red), space = "Lab")
    rgb(ramp(seq(0, 1, length = n)), alpha = alpha, maxColorValue = 255)
}
my.color.GreenRed(10)

```



```{r fig.cap=label}
set.seed(1234)
network(res, cutoff=cutoff, blocks=pair
    , lwd.edge=4
    , show.edge.labels =TRUE
    , color.edge = my.color.GreenRed(100)
    , shape.node=c("rectangle","rectangle")
    )
title(label,adj=1,outer=TRUE,line=-1)
```

Define colors
```{r }
# ce mi je dovolj 19 vrednosti
library(RColorBrewer)
colsh  <-  c(rev(brewer.pal(9, "Blues")), 'grey95', brewer.pal(9, "Reds"))
#colsh <- rev(brewer.pal(11,"RdBu"))
limits <- seq(-1,1,length=length(cols)+1)
limits
```

Reduce matrix used for network. Values below cutoff are converted to zero.
We will leave them out.

```{r }
r <- N[[2]]
keepr <- apply(r, 1, function(x) any(abs(x)>0.000001))
keepc <- apply(r, 2, function(x) any(abs(x)>0.000001))
r <- r[keepr, keepc]
dim(r)
```

```{r }
nr  <- min(nrow(r),40)
nc <- min(ncol(r),20)
# partial output
print(as.table(round(r[1:nr,1:nc],2)), zero.print=".")
```

Heatmap of used correlation matrix

```{r }
if(max(dim(r)) > 30) ind <- my.heatmap(r, col=colsh, zlim=c(-1,1),scale="none") else
ind <- my.heatmap(r, col = colsh, zlim=c(-1,1),scale="none",add.expr=abline(h=0.5+(1:nrow(r)),v=0.5+1:ncol(r),col="white"))
```

```{r }
print(as.table(round(head(r[rev(ind$rowInd),ind$colInd],nr,nc),2)), zero.print=".")
```

```{r result='asis'}
out4 <- ""
out4 <- paste(out4,knit_child("027-plot-networkdiff.rnw",quiet=TRUE))
cat(out4)
```


